export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const EDIT_AND_SAVE_SERVICE = 'EDIT_AND_SAVE_SERVICE';
export const FILTER_SERVICE = 'FILTER_SERVICE';
export const REMOVE_FILTERED_SERVICE = 'REMOVE_FILTERED_SERVICE';
